// Local car catalogue.
//
// This used to be fetched from https://my-revv-api2.herokuapp.com/data, which
// stopped existing when Heroku retired its free dynos — the listing page has
// been rendering an empty grid ever since. The data now ships with the site so
// the demo works offline and can't break again.
//
// `price` is the 440 km/day plan; the shorter plans are derived from it in
// cars.html so a car's three prices stay consistent between renders.
// Photo credits: images/cars/CREDITS.md

const cars = [
  {
    id: "swift",
    name: "Maruti Swift VXi",
    brand: "Maruti",
    segment: "Hatchback",
    fuel: "Petrol",
    transmission: "Manual",
    seats: 5,
    price: 2890,
    url: "./images/cars/swift.jpg",
  },
  {
    id: "baleno",
    name: "Maruti Baleno Zeta AT",
    brand: "Maruti",
    segment: "Hatchback",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: 5,
    price: 3240,
    url: "./images/cars/baleno.jpg",
  },
  {
    id: "dzire",
    name: "Maruti Dzire VXi",
    brand: "Maruti",
    segment: "Sedan",
    fuel: "Petrol",
    transmission: "Manual",
    seats: 5,
    price: 3120,
    url: "./images/cars/dzire.jpg",
  },
  {
    id: "ertiga",
    name: "Maruti Ertiga LXi",
    brand: "Maruti",
    segment: "MUV",
    fuel: "Petrol",
    transmission: "Manual",
    seats: 7,
    price: 3980,
    url: "./images/cars/ertiga.jpg",
  },
  {
    id: "i20",
    name: "Hyundai Elite i20 AT",
    brand: "Hyundai",
    segment: "Hatchback",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: 5,
    price: 3350,
    url: "./images/cars/i20.jpg",
  },
  {
    id: "creta",
    name: "Hyundai Creta SX AT",
    brand: "Hyundai",
    segment: "SUV",
    fuel: "Diesel",
    transmission: "Automatic",
    seats: 5,
    price: 4780,
    url: "./images/cars/creta.jpg",
  },
  {
    id: "verna",
    name: "Hyundai Verna SX AT",
    brand: "Hyundai",
    segment: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: 5,
    price: 4150,
    url: "./images/cars/verna.jpg",
  },
  {
    id: "santro",
    name: "Hyundai Santro Sportz",
    brand: "Hyundai",
    segment: "Hatchback",
    fuel: "Petrol",
    transmission: "Manual",
    seats: 5,
    price: 2650,
    url: "./images/cars/santro.jpg",
  },
  {
    id: "xuv500",
    name: "Mahindra XUV500 W7",
    brand: "Mahindra",
    segment: "SUV",
    fuel: "Diesel",
    transmission: "Manual",
    seats: 7,
    price: 4890,
    url: "./images/cars/xuv500.jpg",
  },
  {
    id: "scorpio",
    name: "Mahindra Scorpio S11",
    brand: "Mahindra",
    segment: "SUV",
    fuel: "Diesel",
    transmission: "Manual",
    seats: 7,
    price: 4560,
    url: "./images/cars/scorpio.jpg",
  },
  {
    id: "thar",
    name: "Mahindra Thar LX 4x4",
    brand: "Mahindra",
    segment: "SUV",
    fuel: "Diesel",
    transmission: "Manual",
    seats: 4,
    price: 5240,
    url: "./images/cars/thar.jpg",
  },
  {
    id: "city",
    name: "Honda City ZX CVT",
    brand: "Honda",
    segment: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: 5,
    price: 4320,
    url: "./images/cars/city.jpg",
  },
  {
    id: "amaze",
    name: "Honda Amaze VX",
    brand: "Honda",
    segment: "Sedan",
    fuel: "Petrol",
    transmission: "Manual",
    seats: 5,
    price: 3080,
    url: "./images/cars/amaze.jpg",
  },
  {
    id: "innova",
    name: "Toyota Innova Crysta GX",
    brand: "Toyota",
    segment: "MUV",
    fuel: "Diesel",
    transmission: "Manual",
    seats: 7,
    price: 5460,
    url: "./images/cars/innova.jpg",
  },
  {
    id: "fortuner",
    name: "Toyota Fortuner 4x2 AT",
    brand: "Toyota",
    segment: "SUV",
    fuel: "Diesel",
    transmission: "Automatic",
    seats: 7,
    price: 6890,
    url: "./images/cars/fortuner.jpg",
  },
  {
    id: "glanza",
    name: "Toyota Glanza G",
    brand: "Toyota",
    segment: "Hatchback",
    fuel: "Petrol",
    transmission: "Manual",
    seats: 5,
    price: 2960,
    url: "./images/cars/glanza.jpg",
  },
];

export default cars;
